## built-in libraries
import os

## custom modules
from Modules.fileHandler import fileHandler
from Modules.toolkit import toolkit

##-------------------start-of-preloader---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

class preloader:

    """

    Preloader is the program that runs before Kudasai.py & Gui.py get started in full swing.\n
    
    """

##-------------------start-of-__init__()---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    def __init__(self) -> None: 

        """
        
        Constructor for the preloader class.\n

        Parameters:\n
        None.\n

        Returns:\n
        None.\n

        """

        self.file_handler = fileHandler()

        self.toolkit = toolkit()

        self.preprocessed_text_path = os.path.join(self.file_handler.output_dir, "preprocessedText.txt") ## path for the preprocessed text
        self.translated_text_path = os.path.join(self.file_handler.output_dir, "translatedText.txt") ## path for translated text

        self.je_check_path = os.path.join(self.file_handler.output_dir, "jeCheck.txt") ## path for je check text (text generated by the translation modules to compare against the translated text)

        self.kairyou_log_path = os.path.join(self.file_handler.output_dir, "Kairyou Results.txt")  ## path for kairyou log (the results of preprocessing)
        self.error_log_path = os.path.join(self.file_handler.output_dir, "error log.txt") ## path for the error log (errors generated by the preprocessing and translation modules)
        self.debug_log_path = os.path.join(self.file_handler.output_dir, "debug log.txt") ## path for debug log (text generated by the translation modules to help with debugging)

        self.setup_needed_files()

##-------------------start-of-setup_needed_files()---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    def setup_needed_files(self) -> None:

        """

        spits out output file paths and creates the required directories for them\n
        
        Parameters:\n
        self (object - Kudasai) : the Kudasai object.\n

        Returns:\n
        None\n

        """

        ## creates the output directory and config directory if they don't exist
        self.file_handler.standard_create_directory(self.file_handler.config_dir)
        self.file_handler.standard_create_directory(self.file_handler.output_dir)

        ## creates and clears the log file
        self.file_handler.logger.clear_log_file()

        ## creates the remaining 5 output files
        self.file_handler.standard_create_file(self.preprocessed_text_path)
        self.file_handler.standard_create_file(self.translated_text_path)
        self.file_handler.standard_create_file(self.je_check_path)
        self.file_handler.standard_create_file(self.kairyou_log_path)
        self.file_handler.standard_create_file(self.error_log_path)
